### PR TITLE
Capybara 2.7

### PR DESCRIPTION
**Pull request by mishaaq**
This commit brings support for Capybara 2.7.0.
Commit https://github.com/jnicklas/capybara/commit/f5ec0dfc7f088f19e867ee044dec2f6ab516fa65 introduced some refactoring of class Capybara::Selector. Extension of this class must be updated to properly define and call custom selectors.

### CODE REVIEW

**Comment by rjaros87** [comment]
:+1:

**Comment by bootstraponline** [comment]
@sbonebrake @maudineormsby thoughts?

**Comment by bootstraponline** [comment]
@rjaros87 @mishaaq would you like to become the maintainers of appium_capybara? I'm not sure if anyone on the team actively maintains it anymore. If so, I'll add you to the team.

**Comment by sbonebrake** [comment]
I think it LGTM. I didn't even realize there was a new version of capybara out. Let me test this branch out locally.

**Comment by bootstraponline** [comment]
cool. 👍

**Comment by sbonebrake** [comment]
My android and ios tests appear to be working fine. I'm going to merge it in. Thanks @mishaaq!

**Comment by mishaaq** [comment]
@bootstraponline Sure I can become a maintainer. Thanks!

**Comment by bootstraponline** [comment]
> @bootstraponline Sure I can become a maintainer. Thanks!

I invited you to the appium `capybara` team. This will allow you to review/merge pull requests. Before merging a PR, you'd want one of the existing team members to approve. For gem releases, those are done by the release team (`maudineormsby`, `sbonebrake`, me). Let me know if you have any questions.

Thanks for contributing to appium!

**Pull request merged**
